research_task:
  description: >
    Conduct thorough research on Base chain (8453) tokens, focusing on protocol metrics, TVL trends, liquidity depth, and engagement from smart followers. Analyze token fundamentals, protocol health, market dynamics, and social signals from influential crypto Twitter users to identify potential index fund candidates.
  expected_output: >
    A detailed analysis of Base chain tokens including:
    - TVL metrics and trends
    - Liquidity depth analysis
    - Smart follower engagement patterns
    - Protocol health indicators
    - Mindshare metrics and community engagement
    - Risk assessment for each potential token
  agent: researcher

reporting_task:
  description: >
    Compile and analyze the research findings into a comprehensive report focusing on Base chain token metrics, market trends, and potential index fund compositions. Include detailed analysis of TVL, liquidity, mindshare metrics, and engagement patterns from influential crypto Twitter users.
  expected_output: >
    A structured report covering:
    - Detailed analysis of identified Base chain tokens
    - Comparative metrics analysis (TVL, liquidity, mindshare)
    - Smart follower sentiment and engagement analysis
    - Risk-reward assessment for potential index compositions
    - Market trend analysis and future projections
    Formatted as markdown without '```'
  output_file: report.md
  agent: reporting_analyst

data_gathering_task:
  description: >
    Collect comprehensive data on Base chain tokens, including TVL metrics, liquidity data, trading volumes, smart contract interactions, and social metrics. Focus on gathering both on-chain data and social signals from influential crypto Twitter users relevant to index fund creation.
  expected_output: >
    A structured dataset containing:
    - Token price and volume data
    - TVL metrics and historical trends
    - Liquidity pool depths and stability metrics
    - Smart follower engagement metrics
    - Social engagement and mindshare metrics
    - Influential crypto voices' sentiment analysis
  agent: researcher

daily_analysis_task:
  description: >
    Lead the daily team discussion about AI Agent tokens we're tracking. Share your latest findings, debate the merits of each project, and discuss whether any deserve a spot in our index. Be direct and honest - what's actually promising versus what's just hype?
  expected_output: >
    Meeting notes capturing the team's honest discussion:
    - What new AI Agent tokens caught our eye and why
    - Debates about existing tokens we're tracking (both good and concerning points)
    - Any red flags or warning signs we should watch
    - Team's current sentiment on each token (bullish/bearish/neutral)
    - Initial thoughts on index inclusion
  agent: reporting_analyst

weekly_decision_task:
  description: >
    After analyzing a week of daily reports and market data, make a final decision on whether to create a new index fund token on Base chain. If approved, specify token selection, weight distribution, and provide comprehensive justification based on collected metrics and smart follower insights.
  expected_output: >
    A detailed decision document including:
    - Go/No-go decision for index fund creation
    - Selected tokens and their weights (if approved)
    - Justification based on:
      * TVL and growth metrics
      * Liquidity analysis
      * Smart follower engagement and sentiment
      * Mindshare and community metrics
      * Risk assessment and mitigation strategies
    - Implementation timeline and monitoring plan
  agent: manager

publish_website_task:
  description: >
    Share our internal meeting notes and discussions about AI Agent tokens with our community. Give them a real inside look at how we evaluate tokens and make decisions. Keep it conversational - like they're sitting in on our team meetings.
  expected_output: >
    An insider's view of our daily discussions:
    - Today's hot topics and debates
    - What tokens we're excited about (and why)
    - What makes us nervous about certain projects
    - Real talk about market trends we're seeing
    - Behind-the-scenes look at our index decisions
  agent: reporting_analyst

publish_twitter_task:
  description: >
    Share key highlights from our daily team discussions about AI Agent tokens. Give followers a peek into our internal debates and thinking process.
  expected_output: >
    A thread capturing the most interesting points from today's meeting:
    - Key debates and disagreements
    - Strongest bull/bear cases made
    - Notable concerns raised
    - Exciting discoveries discussed
  agent: reporting_analyst
